### ISSUE TITLE
Visual artifacts above Chinese language fonts

### ISSUE THREAD

**Issue by youxiachai** [gskinnerTeam/flutter-wonderous-app#11]
in chinese language, render text not clean 

iPhone 12 ios 15.6.1

![QQ图片20220902183849](https://user-images.githubusercontent.com/929502/188122526-cf94460e-36d7-4cf6-bab9-462d7b4a122d.jpg)

**Comment by esDotDev** [comment]
This seems to go away when not using impeller. Also the text also renders significantly more bold than the Skia version:

Impeller
![image](https://user-images.githubusercontent.com/736973/188293635-547c0978-5206-41be-b347-8fe76f53b6d2.png)

Skia
![image](https://user-images.githubusercontent.com/736973/188293640-95d56b02-9115-4bed-945a-4f68eb747773.png)

**Comment by zanderso** [comment]
@esDotDev Could you provide instructions on enabling the Chinese language version? cc @bdero

**Comment by esDotDev** [comment]
> @esDotDev Could you provide instructions on enabling the Chinese language version? cc @bdero

You can switch your test device to Chinese, or just uncomment this line here:
https://github.com/gskinnerTeam/flutter-wonderous-app/blob/4f55aa253616944b19941a5b19dbfa45fa2162ed/lib/logic/locale_logic.dart#L18

**Comment by bdero** [comment]
This is due to glyphs leaking into eachother when sampling from the atlas. One of the more extreme cases demonstrating the issue. Texture atlas is on the left and on-screen text is on the right.

![image](https://user-images.githubusercontent.com/919017/188763989-2d302feb-d6a1-4588-bd76-00699b1f2117.png)

I believe there are two compounding issues:
1. After the linear sampling change, we're including half a pixel too much on the top and left, and excluding half a pixel on the bottom and right. Fixing this should make most of the issue go away.
2. There's either some aspect of the text bounds we're not considering. The emboldened text is legitimately a couple of pixels taller than the non-boldened text, so figuring out this bug may end up resolving the more extreme comma case visible above.

**Comment by bdero** [comment]
This should be fixed by https://github.com/flutter/engine/pull/35960.

**Comment by youxiachai** [comment]
ios 1.0.3 fix
