### ISSUE TITLE
UI thread locks up when loading images on web

### ISSUE THREAD

**Issue by esDotDev** [gskinnerTeam/flutter-wonderous-app#112]
When loading large images on web, the UI thread appears to lockup (the spinner does not move, the animations don't play). Once the image is in memory, the page transitions in properly:

https://github.com/gskinnerTeam/flutter-wonderous-app/assets/736973/d6b590a8-b914-499f-82fb-49ff83cd3385

**Comment by yjbanov** [comment]
I profiled the deployed app, so I'm only seeing obfuscated stacks. I'll need to try it in profile mode later, but here are my early observations:

- I see calls to `MakeAnimatedImageFromEncoded`, which tells me that the app uses wasm image codecs instead of the browser codecs. Wasm codecs are single-threaded and block frames if they do too much work.
- `Image.encodeToBytes` is called, which means the app is _encoding_ images during the animation.

This may be happening transitively through `Image.toByteData`, or it may be happening because the image is being resized while it's decoded (i.e. `targetWidth`/`targetHeight` are specified). These operation are expensive. Additionally, on the web they are single-threaded. Eventually we'll move this to a worker thread, but in general even if we did resize in parallel, I'd recommend resizing images offline as part of the build so it doesn't need to be done on the client. This way you can use the non-blocking browser codecs and the app will always be smooth.

**Comment by esDotDev** [comment]
Ahh, Looks like we are actually wrapping a `ResizeImage` component around the images in order to keep their size in check. 

Removing this seems to fix the issue nicely :)
