### ISSUE TITLE
Some artifact images do not load properly in search view

### ISSUE THREAD

**Issue by DiegoGW** [gskinnerTeam/flutter-wonderous-app#114]
### Steps to reproduce

1. git clone  https://github.com/gskinnerTeam/flutter-wonderous-app.git . As a reference latest commit I have locally is: 
    commit b430fc4f1b4a042bb456f9415447f07b78049105 (HEAD -> main, origin/main, origin/HEAD)
    Author: Shawn <shawn@shawnblais.com>
    Date:   Fri Sep 1 15:48:29 2023 -0600
2. Open Wonderous
3. Go to Petra
4. Artifacts - Browse all artifacts
5. Check that there are missing images for some artifacts

Environment: Pixel 6 - Android 13, Samsung A03 - Andorid 11, iPhone 14 Pro - iOS 16.6, and simulators

### Expected results
All artifact should have a proper image loaded

### Actual results
There are missing images for some artifacts

### Screenshots or Video

<img width="340" alt="Petra missing artifacts images" src="https://github.com/gskinnerTeam/flutter-wonderous-app/assets/11681325/4d63bdb0-f049-4d73-8bf2-fc2000f726da">

**Comment by esDotDev** [comment]
The picture frame element is not a missing image, it's a hidden collectible. If you tap it, it should show an artifact, which in this case is a photo. 

The missing images in the search results is a valid issue though, our app bundles a bunch of pre-selected artifact ids from the MET Api, and some of these artifacts have gone offline since the app was released. 

We're not exactly sure what the correct fix is at the moment but are evaluating options. In the meantime, can you rename this to something like "Some artifact images do not load properly in search view" or something to that effect, and update the OP to remove Steps 1-5 and the associated images?

**Comment by esDotDev** [comment]
We're now self-hosting all images so this has been fixed and should not re-occur

**Comment by DiegoGW** [comment]
Validated in Wonderous latest commit:
commit https://github.com/gskinnerTeam/flutter-wonderous-app/commit/8ac60d46a8bed6c54bcf2df44cccce90a182882f (HEAD -> main, origin/main, origin/HEAD)
Author: Shawn [shawn@gskinner.com](mailto:shawn@gskinner.com)
Date: Thu Oct 5 09:13:02 2023 -0600

Re-ran native_splash generator
