### ISSUE TITLE
Web UX: Map marker positioned differently than mobile

### ISSUE THREAD

**Issue by jaredbell** [gskinnerTeam/flutter-wonderous-app#138]
On the web version, the map marker appears to be positioned bottom-middle vs. middle on mobile. This makes for inaccurate presentation of wonder location. Because web version also includes the ability to zoom in via scroll wheel, you can watch this effect continue as the location gets closer to the actual position.

Web:
<img width="2032" alt="Screenshot 2023-10-27 at 9 41 52 AM" src="https://github.com/gskinnerTeam/flutter-wonderous-app/assets/7093485/ce570086-2243-4df2-bcb7-87e1f164c8bf">

Mobile:
<img width="400" alt="mobile screenshot" src="https://github.com/gskinnerTeam/flutter-wonderous-app/assets/7093485/ec06fafe-53a0-4d3f-aaa0-b6b16d15d7ca">

**Comment by esDotDev** [comment]
Interesting, this is likely an issue with the maps plugin for web but I'll take a look.

**Comment by esDotDev** [comment]
@jaredbell This is a result of this bug with the maps plugin where custom anchor positions are ignored for the marker:
https://github.com/flutter/flutter/issues/80578

Web only supports bottom-center anchoring as that is the default. We're currently using a custom anchor point because of the white background around our pin:
![location-pin](https://github.com/gskinnerTeam/flutter-wonderous-app/assets/736973/35fbfcc0-0238-44c1-bddd-0b5d3eed5eac)

Options:
* Leave it as-is until web plugin bug is fixed
* Replace marker for all platforms removing the background circle
* Create custom marker just for web removing the background circle

**Comment by esDotDev** [comment]
Fixed by d8833d39
