### ISSUE TITLE
Web UX: Browser default scrollbars

### ISSUE THREAD

**Issue by jaredbell** [gskinnerTeam/flutter-wonderous-app#147]
Include browser default scrollbars for persistent indication of scrollable pages and their length.

Currently, touch style indicators only appear when already scrolling.

This would affect:

- Wonder home
- Collection view
- Artifact search
- Timeline

![Standard Scrollbars](https://github.com/gskinnerTeam/flutter-wonderous-app/assets/7093485/4aa33c2f-e950-4847-aab1-674dff113187)

**Comment by esDotDev** [comment]
@jaredbell Just landed this in main. One note:
* ArtifactSearch had this intentionally turned off because 
  * it's a dynamic list and the scrollbacr "knob" size is always fluctuating. 
  * performance is pretty poor when trying to drag the scroll bar quickly.

I've left it off for this view for now, but LMK if you think it's worth turning on.
